//// BeachLocation_mobile.js

const BeachLocation = ({ lightText, showMoreStyle, showSeeMore, hiddenStyle, showMoreLocations }) => {

  return (
    <div className="getawayLocation">
      <div className="getawayWrapper">
        <button>Dauphin Island<br/><span style={lightText}>Alabama</span></button>
        <button>Fort Morgan<br/><span style={lightText}>Alabama</span></button>
        <button>Gulf Shores<br/><span style={lightText}>Alabama</span></button>
        <button>Bruny Island<br/><span style={lightText}>Australia</span></button>
        <button>Crescent Head<br/><span style={lightText}>Australia</span></button>
        <button>Gerringong<br/><span style={lightText}>Australia</span></button>
        <button>Hamilton Island<br/><span style={lightText}>Australia</span></button>
        <button>Lancelin<br/><span style={lightText}>Australia</span></button>
        <button>Melbourne Beach<br/><span style={lightText}>Australia</span></button>
        <button>Moonta Bay<br/><span style={lightText}>Australia</span></button>
        <button>Ocean Grove<br/><span style={lightText}>Australia</span></button>
        {showSeeMore ? <button onClick={showMoreLocations} style={showMoreStyle}>Show more</button> : <button>Majorca<br/><span style={lightText}>Balearic Islands</span></button>}
        <div style={hiddenStyle} className="hiddenLocations">
          <button>Big Sur<br/><span style={lightText}>California</span></button>
          <button>Bodega Bay<br/><span style={lightText}>California</span></button>
          <button>Cambria<br/><span style={lightText}>California</span></button>
          <button>Cayucos<br/><span style={lightText}>California</span></button>
          <button>Huntington Beach<br/><span style={lightText}>California</span></button>
          <button>La Jolla Shores Beach<br/><span style={lightText}>California</span></button>
          <button>Laguna Beach<br/><span style={lightText}>California</span></button>
          <button>Long Beach<br/><span style={lightText}>California</span></button>
          <button>Malibu<br/><span style={lightText}>California</span></button>
          <button>Mission Beach<br/><span style={lightText}>California</span></button>
          <button>Newport Beach<br/><span style={lightText}>California</span></button>
          <button>Oceanside<br/><span style={lightText}>California</span></button>
          <button>Palm Springs<br/><span style={lightText}>California</span></button>
          <button>Pismo Beach<br/><span style={lightText}>California</span></button>
          <button>Santa Cruz<br/><span style={lightText}>California</span></button>
          <button>Santa Monica<br/><span style={lightText}>California</span></button>
          <button>Sea Ranch<br/><span style={lightText}>California</span></button>
          <button>Playa Blanca<br/><span style={lightText}>Canarias</span></button>
          <button>Fuerteventura<br/><span style={lightText}>Canary Islands</span></button>
          <button>Puerto Del Carmen<br/><span style={lightText}>Canary Islands</span></button>
          <button>Tenerife<br/><span style={lightText}>Canary Islands</span></button>
          <button>Ayia Napa<br/><span style={lightText}>Cyprus</span></button>
          <button>Bethany Beach<br/><span style={lightText}>Delaware</span></button>
          <button>Dewey Beach<br/><span style={lightText}>Delaware</span></button>
          <button>Blackpool<br/><span style={lightText}>England</span></button>
          <button>Isle of Wight<br/><span style={lightText}>England</span></button>
          <button>Newquay<br/><span style={lightText}>England</span></button>
          <button>Weymouth<br/><span style={lightText}>England</span></button>
          <button>Albufeira<br/><span style={lightText}>Faro District</span></button>
          <button>Alys Beach<br/><span style={lightText}>Florida</span></button>
          <button>Anna Maria Island<br/><span style={lightText}>Florida</span></button>
          <button>Boca Grande<br/><span style={lightText}>Florida</span></button>
          <button>Bradenton<br/><span style={lightText}>Florida</span></button>
          <button>Cape San Blas<br/><span style={lightText}>Florida</span></button>
          <button>Captiva<br/><span style={lightText}>Florida</span></button>
          <button>Clearwater Beach<br/><span style={lightText}>Florida</span></button>
          <button>Cocoa Beach<br/><span style={lightText}>Florida</span></button>
          <button>Daytona Beach<br/><span style={lightText}>Florida</span></button>
          <button>Destin<br/><span style={lightText}>Florida</span></button>
          <button>Englewood<br/><span style={lightText}>Florida</span></button>
          <button>Fort Lauderdale<br/><span style={lightText}>Florida</span></button>
          <button>Fort Myers Beach<br/><span style={lightText}>Australia</span></button>
          <button>Fort Walton Beach<br/><span style={lightText}>Florida</span></button>
          <button>Grayton Beach<br/><span style={lightText}>Florida</span></button>
          <button>Gulf of Mexico<br/><span style={lightText}>Florida</span></button>
          <button>Indian Rocks Beach<br/><span style={lightText}>Florida</span></button>
          <button>Islamorada<br/><span style={lightText}>Florida</span></button>
          <button>Jacksonville Beach<br/><span style={lightText}>Florida</span></button>
          <button>Key Largo<br/><span style={lightText}>Florida</span></button>
          <button>Madeira Beach<br/><span style={lightText}>Florida</span></button>
          <button>Marathon<br/><span style={lightText}>Florida</span></button>
          <button>Marco Island<br/><span style={lightText}>Florida</span></button>
          <button>Mexico Beach<br/><span style={lightText}>Florida</span></button>
          <button>Miami Beach<br/><span style={lightText}>Florida</span></button>
          <button>Miami<br/><span style={lightText}>Florida</span></button>
          <button>Miramar Beach<br/><span style={lightText}>Florida</span></button>
          <button>Naples<br/><span style={lightText}>Florida</span></button>
          <button>Navarre Beach<br/><span style={lightText}>Florida</span></button>
          <button>New Smyrna Beach<br/><span style={lightText}>Florida</span></button>
          <button>Okaloosa Island<br/><span style={lightText}>Florida</span></button>
          <button>Panama City Beach<br/><span style={lightText}>Florida</span></button>
          <button>Penascola Beach<br/><span style={lightText}>Florida</span></button>
          <button>Perdido Key<br/><span style={lightText}>Florida</span></button>
          <button>Rosemary Beach<br/><span style={lightText}>Florida</span></button>
          <button>Saint George Island<br/><span style={lightText}>Florida</span></button>
          <button>Santa Rosa Beach<br/><span style={lightText}>Florida</span></button>
          <button>Sarasota<br/><span style={lightText}>Florida</span></button>
          <button>Seagrove Beach<br/><span style={lightText}>Florida</span></button>
          <button>Seaside<br/><span style={lightText}>Florida</span></button>
          <button>South Beach<br/><span style={lightText}>Florida</span></button>
          <button>St. Augustine Beach<br/><span style={lightText}>Florida</span></button>
          <button>St. Pete Beach<br/><span style={lightText}>Florida</span></button>
          <button>Tampa<br/><span style={lightText}>Florida</span></button>
          <button>West Palm Beach<br/><span style={lightText}>Florida</span></button>
          <button>Bora Bora<br/><span style={lightText}>French Polynesia</span></button>
          <button>Tybee Island<br/><span style={lightText}>Georgia</span></button>
          <button>Honolulu<br/><span style={lightText}>Hawaii</span></button>
          <button>Kailua-Kona<br/><span style={lightText}>Hawaii</span></button>
          <button>Kapalua<br/><span style={lightText}>Hawaii</span></button>
          <button>Kauai<br/><span style={lightText}>Hawaii</span></button>
          <button>Kihei<br/><span style={lightText}>Hawaii</span></button>
          <button>Ko Olina Beach<br/><span style={lightText}>Hawaii</span></button>
          <button>Maui<br/><span style={lightText}>Hawaii</span></button>
          <button>Topsail Island<br/><span style={lightText}>Hawaii</span></button>
          <button>Old Orchard Beach<br/><span style={lightText}>Maine</span></button>
          <button>Wells<br/><span style={lightText}>Maine</span></button>
          <button>Cape Cod<br/><span style={lightText}>Massachussetts</span></button>
          <button>Nantucket<br/><span style={lightText}>Massachussetts</span></button>
          <button>Biloxi<br/><span style={lightText}>Massachussetts</span></button>
          <button>Avalon<br/><span style={lightText}>New Jersey</span></button>
          <button>Jersey Shore<br/><span style={lightText}>New Jersey</span></button>
          <button>North Wildwood<br/><span style={lightText}>New Jersey</span></button>
          <button>Ocean City<br/><span style={lightText}>New Jersey</span></button>
          <button>Sea Isle City<br/><span style={lightText}>New Jersey</span></button>
          <button>Stone Harbor<br/><span style={lightText}>New Jersey</span></button>
          <button>Hyams Beach<br/><span style={lightText}>New South Wales</span></button>
          <button>Fire Island<br/><span style={lightText}>New York</span></button>
          <button>Montauk<br/><span style={lightText}>New York</span></button>
          <button>Ocean Beach<br/><span style={lightText}>New York</span></button>
          <button>Atlantic Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Carolina Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Corolla<br/><span style={lightText}>North Carolina</span></button>
          <button>Holden Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Kitty Hawk<br/><span style={lightText}>North Carolina</span></button>
          <button>Kure Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Nags Head<br/><span style={lightText}>North Carolina</span></button>
          <button>Ocean Isle Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Sunset Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Surf City<br/><span style={lightText}>North Carolina</span></button>
          <button>Wilmington<br/><span style={lightText}>North Carolina</span></button>
          <button>Wrightsville Beach<br/><span style={lightText}>North Carolina</span></button>
          <button>Grand Bend<br/><span style={lightText}>Ontario</span></button>
          <button>Sauble Beach<br/><span style={lightText}>Ontario</span></button>
          <button>Wasaga Beach<br/><span style={lightText}>Ontario</span></button>
          <button>Cannon Beach<br/><span style={lightText}>Oregon</span></button>
          <button>Seaside<br/><span style={lightText}>Oregon</span></button>
          <button>Carvoeiro<br/><span style={lightText}>Portugal</span></button>
          <button>Gold Coast<br/><span style={lightText}>Queensland</span></button>
          <button>Moreton Island<br/><span style={lightText}>Queensland</span></button>
          <button>Block Island<br/><span style={lightText}>Rhode Island</span></button>
          <button>Puerto Penasco<br/><span style={lightText}>Sonora</span></button>
          <button>Charleston Oceanfront Villas, Folly Beach<br/><span style={lightText}>South Carolina</span></button>
          <button>Edisto Beach<br/><span style={lightText}>South Carolina</span></button>
          <button>Folly Beach<br/><span style={lightText}>South Carolina</span></button>
          <button>Fripp Island<br/><span style={lightText}>South Carolina</span></button>
          <button>Isle of Palms<br/><span style={lightText}>South Carolina</span></button>
          <button>Kiawah Island<br/><span style={lightText}>South Carolina</span></button>
          <button>Myrtle Beach<br/><span style={lightText}>South Carolina</span></button>
          <button>Pawleys Beach<br/><span style={lightText}>South Carolina</span></button>
          <button>Seabrook Island<br/><span style={lightText}>South Carolina</span></button>
          <button>Sullivan's Island<br/><span style={lightText}>South Carolina</span></button>
          <button>Surfside Beach<br/><span style={lightText}>South Carolina</span></button>
          <button>Alicante<br/><span style={lightText}>Spain</span></button>
          <button>Costa Adeje<br/><span style={lightText}>Spain</span></button>
          <button>Costa Del Sol<br/><span style={lightText}>Spain</span></button>
          <button>Fuengirola<br/><span style={lightText}>Spain</span></button>
          <button>Los Cristianos<br/><span style={lightText}>Spain</span></button>
          <button>Corpus Christi<br/><span style={lightText}>Texas</span></button>
          <button>Port Aransas<br/><span style={lightText}>Texas</span></button>
          <button>South Padre Island<br/><span style={lightText}>Texas</span></button>
          <button>Surfside Beach<br/><span style={lightText}>Texas</span></button>
          <button>Bournemouth<br/><span style={lightText}>United Kingdom</span></button>
          <button>New Quay<br/><span style={lightText}>United Kingdom</span></button>
          <button>Anglesea<br/><span style={lightText}>Victoria</span></button>
          <button>Abersoch<br/><span style={lightText}>Wales</span></button>
          <button>Seabrook<br/><span style={lightText}>Washington</span></button>
          <button>Jurien Bay<br/><span style={lightText}>Western Australia</span></button>
        </div>
      </div>
    </div>
  )
}

export default BeachLocation;
